# Default kvdb server address and port.
addr = "127.0.0.1:5200"

# kvdb grpc server address and port,
# if you don't define it in config file, grpc server will not enable.
grpc_addr = "127.0.0.1:5300"

# Default kvdb data dir: /tmp/kvdb.
# Do not use the default path before you use it in production.
dir_path = "/tmp/kvdb"

# Default db file size: 16MB.
block_size = 16777216

# DB file read and write method, 0:FileIO 1:MMap.
rw_method = 0

# The index mode, 0: KeyValueMemMode, 1: KeyOnlyMemMode.
idx_mode = 1

# The max size of key: 1MB.
max_key_size = 1048576

# The max size of value: 8MB.
max_value_size = 8388608

# Flush the db file to disk of every write operation.
sync = false

# The threshold for db file reclaiming.
merge_threshold = 64
